### ISSUE TITLE
RAML Parser Expression Models - missing securedBy property

### ISSUE THREAD

**Issue by zombieabe** [raml-org/raml-dotnet-parser#2]
I just wanted to find out if there was any plan to accommodate the securedBy property on any of the ResourceType, and/or Verb Models?

**Comment by woodp** [comment]
Not sure I understand the question. 
securedBy can be used at the root or method levels and it can be used in a resource type (at the method level).

If this is a question regarding the specification of RAML then I think https://github.com/raml-org/raml-spec would be a better place to ask.

**Comment by zombieabe** [comment]
Hi Pedro

Thanks for the quick reply, sorry if this was vague. I hope this can clear it up. In the RAML Spec you should be able to secure the entire api and/or a resource specifically.

eg:(directly from the spec)

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#%RAML 0.8
title: Dropbox API
version: 1
baseUri: https://api.dropbox.com/{version}
securedBy: [oauth_2_0] <-- api level security
securitySchemes:
    - oauth_2_0: !include oauth_2_0.yml
    - oauth_1_0: !include oauth_1_0.yml
/users:
    get:
        securedBy: [oauth_2_0, oauth_1_0] <-- resource level specific security
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Currently the raml-dotnet-parser only supports api level security. 
So if i had to load this document, i would have no way of knowing that the users get resource route had additional security.

I hope this clears things up.

Regards.

**Comment by woodp** [comment]
Hi @zombieabe thanks for the explanation.

Actually the parser supports securedBy at the method level as specified by the RAML spec.

In [Method class](https://github.com/raml-org/raml-dotnet-parser/blob/master/Raml.Parser/Expressions/Method.cs) you have a SecuredBy property, if you specify a "securedBy" at the method level it will fill that property.

If you have a RAML that doesn't parse as expected please post it here.
