### ISSUE TITLE
Exception when loading raml document

### ISSUE THREAD

**Issue by kdcarlisle42** [raml-org/raml-dotnet-parser#4]
I've download the source for the parser and added it to a simple console app project.  I've compiled the project (success) and then tried to run (exception thrown).  The code that loads the file is...

async Task<Raml.Parser.Expressions.RamlDocument> ParseRamlFile(string ramlFileName) {
     Raml.Parser.RamlParser raml_parser = new Raml.Parser.RamlParser();
     return  await raml_parser.LoadAsync(ramlFileName);
}

which throws the following error...

Error parsing: while reading c:/wip/traits/status_codes.raml
cannot read c:/wip/traits/status_codes.raml (Error: ENOENT, open 'c:\wip\traits\status_codes.raml')

Here is the raml source

#%RAML 0.8
---
title: Fragomen Connect
version: v1
protocols: [HTTP,HTTPS]
baseUri: http://ims-uat.rst.fragomen.net
traits:
  - !include traits/status_codes.raml
securitySchemes:
  - basic:
      type: Basic Authentication
/utl/v1/network:
  /connect:
    get: !include v1/utl/network/route/get/connect.raml
    /anonymous:
      get: !include v1/utl/network/route/get/connect_anonymous.raml

---------------

All of the referenced files are there.  If I run the raml2html tool, it will process the file and generate the html output (and it is correct).  I did test using the 'box.raml' file that was provided with the Ram.Parser.Tests project.  It worked, but I don't think it had any external references.

Is there something that needs to be set, path wise, before loading a raml document?

**Comment by woodp** [comment]
I was able to reproduce this. 
Fix will come soon, in the meantime you can use method LoadRamlAsync(string raml, string path)

**Comment by woodp** [comment]
Fixed in release v 0.8.104
